name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: deploy
    env: 
      DOCKER_IMAGE: ghcr.io/lfgappeu/lfg-api:latest

    permissions: 
      contents: read
      packages: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (for building images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build and Push Docker Image to GitHub Container Registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

      # Step 5: Deploy to ec2
      - name: Deploy to my EC2 instance
        uses: appleboy/ssh-action@master
        env: 
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ env.DOCKER_IMAGE }}
            echo ${{ DOCKER_IMAGE }}
            echo $DOCKER_IMAGE

            # Stop and remove any existing container
            docker rm -f lfg || true

            # Pull the latest Docker image
            docker pull ghcr.io/lfgappeu/lfg-api:latest

            # Run the new container
            docker run -d --name lfg -p 80:3000 ghcr.io/lfgappeu/lfg-api:latest

            # make sure container is running
            docker ps --format '{{.Names}}' | grep -q "lfg" || { echo "Error: Container is not running."; exit 1; }