name: DB Migration

on:
  workflow_dispatch: # to allow manual triggering
  push:
    branches:
      - master
    paths:
        - "src/db/migrations/**"
        - ".github/workflows/migrate.yaml"

  pull_request:
    branches:
      - master
    paths:
        - "src/db/migrations/**"
        - ".github/workflows/migrate.yaml"

jobs:
  migration:
    runs-on: ubuntu-latest

    environment: deploy

    permissions: 
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: deps
        run: npm install dotenv

      - name: Migrate
        run: | 
          export POSTGRES_URL=${{secrets.DOCKER_POSTGRES_URL}}
          export DB_CA="${{secrets.DOCKER_DB_CA}}"
          echo "${{secrets.SSH_KEY}}" > key.pem
          
          chmod 600 key.pem

          # create ssh tunnel
          ssh -i key.pem -o StrictHostKeyChecking=no -L ${{secrets.MIGRATION_URL}} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} -fN 

          # run migration
          npx drizzle-kit migrate
